начальный коммит для 1-ого ревью диплома
InnaMrzn/java-explore-with-me pull request #1
Opened 2022-10-28 14:28 UTC by InnaMrzn

2022-10-28 16:26 UTC, damirovna requested changes
Отличная работа, коректно составлена модель, очень хорошая структура проекта, правильная работа со сборкой.

Над чем нужно поработать:
1) Нужно сделать схему БД более  жёсткой, ограничить размеры полей
2) Обязательно нужно переделать логику работы с просмотрами, эта информация должна быть получена из сервиса статистики и не храниться в БД основного сервиса.

2022-10-28 16:26 UTC, damirovna commented on ewm-main/src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS USERS
[Нужно исправить] 

Пожалуйста, ограничьте размеры полей разумными ограничениями, например максимально возможный размер адреса электронной почты можно найти в https://www.rfc-editor.org/rfc/rfc5321#section-4.5.3

2022-10-28 16:26 UTC, damirovna commented on ewm-main/src/main/resources/schema.sql
> +    VIEWS BIGINT,
[Нужно исправить]

Информацию о просмотрах необходимо получать из сервиса статистики, это требование ТЗ.

2022-10-28 16:26 UTC, damirovna commented on ewm-main/src/main/resources/schema.sql
> +    EVENT_STATE
[Можно лучше]

Можно добавить дефолтное значение 'PENDING'

2022-10-28 16:26 UTC, damirovna commented on ewm-main/src/main/java/ru/practicum/dto/NewCategoryDto.java
> +    private String name;
[Нужно исправить]

Нужно добавить аннотации @Size и @NotBlank

2022-10-28 16:26 UTC, damirovna commented on ewm-main/src/main/java/ru/practicum/dto/NewCompilationDto.java
> +    private final String title;
[Нужно исправить]

Нужно добавить аннотацию @SiZe

2022-10-28 16:26 UTC, damirovna commented on ewm-main/src/main/java/ru/practicum/dto/NewEventDto.java
> +    int participantLimit;
[Нужно исправить]

Нужно добавить аннотацию запрещающую отрицательное количество участников

2022-10-28 16:26 UTC, damirovna commented on ewm-main/src/main/java/ru/practicum/dto/EventFullDto.java
> +public class EventFullDto {
[На подумать]

Обратите внимание, что данный класс содержит все поля класса EventShortDto, можно использовать принципы ООП для уменьшения количества кода

2022-10-28 16:26 UTC, damirovna commented on ewm-main/src/main/java/ru/practicum/dto/ParticipationRequestDto.java
> +    String status;
[Можно лучше]

Логичнее это поле сделать сделать enum.

2022-10-28 16:26 UTC, damirovna commented on ewm-main/src/main/java/ru/practicum/dto/UpdateEventRequest.java
> +public class UpdateEventRequest {
[Нужно исправить]

На полях этого класса должны быть те же аннотации, что и на аналогичных полях класса NewEventDto, так при обновлении нужно так же поддерживать корректность данных, как и при создании.

2022-10-31 06:46 UTC, InnaMrzn commented on ewm-main/src/main/resources/schema.sql
> +    VIEWS BIGINT,
Переделала получение просмотров из сервиса статистики, динамически обновляется

2022-10-31 07:01 UTC, InnaMrzn commented on ewm-main/src/main/resources/schema.sql
> +    EVENT_STATE
Добавила

2022-10-31 07:05 UTC, InnaMrzn commented on ewm-main/src/main/java/ru/practicum/dto/NewCategoryDto.java
> +    private String name;
Добавила

2022-10-31 07:06 UTC, InnaMrzn commented on ewm-main/src/main/java/ru/practicum/dto/NewCompilationDto.java
> +    private final String title;
добавила

2022-10-31 07:07 UTC, InnaMrzn commented on ewm-main/src/main/java/ru/practicum/dto/NewEventDto.java
> +    int participantLimit;
Добавила

2022-10-31 07:08 UTC, InnaMrzn commented on ewm-main/src/main/java/ru/practicum/dto/EventFullDto.java
> +public class EventFullDto {
Сделала их наследниками нового абстрактного класса EventDto

2022-10-31 07:13 UTC, InnaMrzn commented on ewm-main/src/main/java/ru/practicum/dto/ParticipationRequestDto.java
> +    String status;
специально сделала его String, так как это поле используется для сериализации информации в json и в маппере я его как раз заполняю значением из enum. Если сделать его enum, то боюсь что json не будет его корректно серилизовать...

2022-10-31 07:19 UTC, InnaMrzn commented on ewm-main/src/main/java/ru/practicum/dto/UpdateEventRequest.java
> +public class UpdateEventRequest {
сделала

2022-10-31 07:19 UTC, InnaMrzn commented on ewm-main/src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS USERS
сделала

2022-10-31 14:47 UTC, damirovna approved these changes
Поздравляю вас со сдачей диплома!

2022-10-31 14:47 UTC, damirovna commented on ewm-main/src/main/java/ru/practicum/dto/ParticipationRequestDto.java
> +    String status;
Если будет свободное время и желание попробовать что-то новое, то поробуйте)

2022-10-31 16:40 UTC, merged